/*
 * Copyright (C) 2015-2023 Objectos Software LTDA.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package objectos.selfgen.html;

import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;
import objectos.code.ClassName;

final class HtmlStep extends ThisTemplate {

  HtmlStep(HtmlSelfGen spec) {
    super(spec);
  }

  @Override
  final String contents() {
    className(ClassName.of(WAY_PACKAGE, "Html"));

    return code."""
    /*
     * Copyright (C) \{COPYRIGHT_YEARS} Objectos Software LTDA.
     *
     * Licensed under the Apache License, Version 2.0 (the "License");
     * you may not use this file except in compliance with the License.
     * You may obtain a copy of the License at
     *
     * http://www.apache.org/licenses/LICENSE-2.0
     *
     * Unless required by applicable law or agreed to in writing, software
     * distributed under the License is distributed on an "AS IS" BASIS,
     * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
     * See the License for the specific language governing permissions and
     * limitations under the License.
     */
    package \{packageName};
    \{importList}
    /**
     * The Objectos HTML main class.
     */
    public final class \{simpleName} {

      private \{simpleName}() {}

      // The code below was generated by objectos.selfgen.HtmlSpec. Do not edit!

    \{attributes()}
    \{elements()}
    }
    """;
  }
  
  private String attributes() {
    return code."""
      /**
       * Represents an instruction that generates part of the output of an HTML
       * template.
       *
       * <p>
       * Unless noted references to a particular instruction MUST NOT be reused.
       */
      public sealed interface Instruction {}
    
      /**
       * An attribute instruction in an HTML template.
       */
      public sealed interface AttributeInstruction extends Instruction {}
    
      private static final class HtmlAttributeInstruction implements AttributeInstruction {}
    
      static final AttributeInstruction ATTRIBUTE = new HtmlAttributeInstruction();
    
    \{templateAttributes()}    
    \{compilerAttributes()}""";
  }
  
  private String templateAttributes() {
    return code."""
      /**
       * Provides the HTML attributes template methods.
       */
      public sealed static abstract class TemplateAttributes {
      
        TemplateAttributes() {}
  
    \{templateAttributesMethods()}
        abstract CompilerAttributes $attributes();
        
      }
    """;
  }
  
  private String templateAttributesMethods() {
    return attributeMethods((name, attribute) -> {
      AttributeKind kind;
      kind = attribute.kind();

      if (kind.isString()) {
        return code."""
                /**
                 * Generates the {@code \{attribute.name()}} attribute with the specified value.
                 *
                 * @param value
                 *        the value of the attribute
                 *
                 * @return an instruction representing this attribute.
                 */
                protected final AttributeInstruction \{name}(String value) {
                  return $attributes().\{name}(value);
                }
            """;
      } else {
        return code."""
                /**
                 * Generates the {@code \{attribute.name()}} boolean attribute.
                 *
                 * @return an instruction representing this attribute.
                 */
                protected final AttributeInstruction \{name}() {
                  return $attributes().\{name}();
                }
            """;
      }
    });
  }
  
  private String compilerAttributes() {
    return code."""
      /**
       * Provides the HTML attributes compiler methods.
       */
      public sealed interface CompilerAttributes permits Compiler {
    
    \{compilerAttributesMethods()}
      }
    """;
  }
  
  private String compilerAttributesMethods() {
    return attributeMethods((name, attribute) -> {
      AttributeKind kind;
      kind = attribute.kind();

      if (kind.isString()) {
        return code."""
                /**
                 * Generates the {@code \{attribute.name()}} attribute with the specified value.
                 *
                 * @param value
                 *        the value of the attribute
                 *
                 * @return an instruction representing this attribute.
                 */
                AttributeInstruction \{name}(String value);
            """;
      } else {
        return code."""
                /**
                 * Generates the {@code \{attribute.name()}} boolean attribute.
                 *
                 * @return an instruction representing this attribute.
                 */
                AttributeInstruction \{name}();
            """;
      }
    });
  }
  
  private String elements() {
    return code."""
        /**
         * An element instruction in an HTML template.
         */
        public sealed interface ElementInstruction extends Instruction {}
      
        private static final class HtmlElementInstruction implements ElementInstruction {}
      
        static final ElementInstruction ELEMENT = new HtmlElementInstruction();
      
      \{templateElements()}
      \{compilerElements()}""";
  }
  
  private String templateElements() {
    return code."""
        /**
         * Provides the HTML elements template methods.
         */
        public non-sealed static abstract class TemplateElements extends TemplateAttributes {
      
          /**
           * Sole constructor.
           */
          TemplateElements() {}
  
          /**
           * Generates the {@code <!DOCTYPE html>} doctype.
           */
          protected final void doctype() {
            $elements().doctype();
          }
  
      \{templateElementsMethods()}
          abstract CompilerElements $elements();
        
        }
      """;
  }
  
  private String templateElementsMethods() {
    List<String> methods;
    methods = new ArrayList<>();

    TemplateSpec template;
    template = spec.template();

    for (var element : spec.elements()) {
      String methodName;
      methodName = element.methodName();

      String paramTypeName;
      paramTypeName = element.hasEndTag() ? "Instruction" : "AttributeInstruction";

      methods.add(code."""
          /**
           * Generates the {@code \{element.name()}} element with the specified content.
           *
           * @param contents
           *        the attributes and children of this element
           *
           * @return an instruction representing this element.
           */
          protected final ElementInstruction \{methodName}(\{paramTypeName}... contents) {
            return $elements().\{methodName}(contents);
          }
      """);

      if (template.shouldIncludeText(element)) {

        methods.add(code."""
            /**
             * Generates the {@code \{element.name()}} element with the specified text.
             *
             * @param text
             *        the text value of this element
             *
             * @return an instruction representing this element.
             */
            protected final ElementInstruction \{methodName}(String text) {
              return $elements().\{methodName}(text);
            }
        """);

      } else if (spec.isAmbiguous(element)) {

        methods.add(code."""
            /**
             * Generates the {@code \{element.name()}} attribute or element with the specified text.
             *
             * @param text
             *        the text value of this attribute or element
             *
             * @return an instruction representing this attribute or element.
             */
            protected final ElementInstruction \{methodName}(String text) {
              return $elements().\{methodName}(text);
            }
        """);

      }
    }

    return methods.stream().collect(Collectors.joining("\n"));
  }

  private String compilerElements() {
    return code."""
      /**
       * Provides the HTML elements compiler methods.
       */
      public sealed interface CompilerElements permits Compiler {
    
        /**
         * Generates the {@code <!DOCTYPE html>} doctype.
         */
        void doctype();

    \{compilerElementsMethods()}
      }
    """;
  }
  
  private String compilerElementsMethods() {
    List<String> methods;
    methods = new ArrayList<>();

    TemplateSpec template;
    template = spec.template();

    for (var element : spec.elements()) {
      String methodName;
      methodName = element.methodName();

      String paramTypeName;
      paramTypeName = element.hasEndTag() ? "Instruction" : "AttributeInstruction";

      methods.add(code."""
          /**
           * Generates the {@code \{element.name()}} element with the specified content.
           *
           * @param contents
           *        the attributes and children of this element
           *
           * @return an instruction representing this element.
           */
          ElementInstruction \{methodName}(\{paramTypeName}... contents);
      """);

      if (template.shouldIncludeText(element)) {

        methods.add(code."""
            /**
             * Generates the {@code \{element.name()}} element with the specified text.
             *
             * @param text
             *        the text value of this element
             *
             * @return an instruction representing this element.
             */
            ElementInstruction \{methodName}(String text);
        """);

      } else if (spec.isAmbiguous(element)) {

        methods.add(code."""
            /**
             * Generates the {@code \{element.name()}} attribute or element with the specified text.
             *
             * @param text
             *        the text value of this attribute or element
             *
             * @return an instruction representing this attribute or element.
             */
            ElementInstruction \{methodName}(String text);
        """);

      }
    }

    return methods.stream().collect(Collectors.joining("\n"));
  }

}