/*
 * Copyright (C) 2015-2024 Objectos Software LTDA.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package objectos.selfgen;

final class CarbonClassGen extends CarbonTemplate {

  public CarbonClassGen(CarbonSpec spec) {
    super(spec);
  }

  @Override
  final String contents() {
    className("Carbon");

    return code."""
    /*
     * Copyright (C) \{COPYRIGHT_YEARS} Objectos Software LTDA.
     *
     * Licensed under the Apache License, Version 2.0 (the "License");
     * you may not use this file except in compliance with the License.
     * You may obtain a copy of the License at
     *
     * http://www.apache.org/licenses/LICENSE-2.0
     *
     * Unless required by applicable law or agreed to in writing, software
     * distributed under the License is distributed on an "AS IS" BASIS,
     * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
     * See the License for the specific language governing permissions and
     * limitations under the License.
     */
    package \{packageName};
    \{importList}
    /**
     * The <strong>Objectos Carbon UI</strong> main class.
     *
     * <p>
     * Objectos Carbon UI is an implementation of the Carbon Design System in pure
     * Java.
     */
    public final class \{simpleName} {

      //
      // The code below was generated by objectos.selfgen.CarbonMain.
      //
      // DO NOT EDIT!
      //

    \{attributes()}
    \{hierarchy()}
    \{components()}
    }
    """;
  }

  private String attributes() {
    return code."""
      // attributes
    
      /**
       * The nested types of this interface represent the Carbon UI attributes.
       */
      public sealed interface Attribute {
      }
    """;
  }

  private String hierarchy() {
    return code."""
      // hierarchy
    
      /**
       * A nested type of this interface can be used as a child of the corresponding
       * component.
       */
      public sealed interface ChildOf {
      }
    """;
  }

  private String components() {
    return code."""
      // components
    
      public sealed interface Component {}
    
      @SuppressWarnings("unused")
      private static final class NoImpl implements Attribute, ChildOf, Component {}
    """;
  }

}