/*
 * Copyright (C) 2015-2023 Objectos Software LTDA.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package objectos.selfgen.html;

import static org.testng.Assert.assertEquals;

import org.testng.annotations.Test;

public class GeneratedAttributeNameStepTest {

  @Test(description = "it should generate an class for each distinct attribute defined")
  public void execute() {
    HtmlSelfGen spec;
    spec = new HtmlSelfGen() {
      @Override
      protected final void definition() {
        rootElement()
            .attribute("hidden").booleanType()
            .attributeEnd();

        element("meta")
            .attribute("charset")
            .noEndTag();
      }
    }.prepare();

    GeneratedAttributeNameStep template;
    template = new GeneratedAttributeNameStep(spec);

    assertEquals(
        template.toString(),

        """
        /*
         * Copyright (C) 2015-2024 Objectos Software LTDA.
         *
         * Licensed under the Apache License, Version 2.0 (the "License");
         * you may not use this file except in compliance with the License.
         * You may obtain a copy of the License at
         *
         * http://www.apache.org/licenses/LICENSE-2.0
         *
         * Unless required by applicable law or agreed to in writing, software
         * distributed under the License is distributed on an "AS IS" BASIS,
         * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
         * See the License for the specific language governing permissions and
         * limitations under the License.
         */
        package objectos.html;

        // Generated by objectos.selfgen.HtmlSpec. Do not edit!
        abstract class GeneratedAttributeName {

          GeneratedAttributeName() {}

          /**
           * The {@code charset} attribute.
           */
          public static final AttributeName CHARSET = WayAttributeNameBuilder.create("charset", false);

          /**
           * The {@code hidden} attribute.
           */
          public static final AttributeName HIDDEN = WayAttributeNameBuilder.create("hidden", true);

        }
        """
    );
  }

}
