/*
 * Copyright (C) 2015-2023 Objectos Software LTDA.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package objectos.selfgen.html;

import static org.testng.Assert.assertEquals;

import org.testng.annotations.Test;

public class HtmlElementNameGeneratedStepTest {

  @Test
  public void execute() {
    HtmlSelfGen spec;
    spec = TestingHtmlSelfGen.SPEC;

    HtmlElementNameGeneratedStep template;
    template = new HtmlElementNameGeneratedStep(spec);

    assertEquals(
        template.toString(),

        """
/*
 * Copyright (C) 2015-2024 Objectos Software LTDA.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package objectos.way;

/**
 * Provides the names of the standard HTML elements.
 */
// Generated by objectos.selfgen.HtmlSpec. Do not edit!
abstract class HtmlElementNameGenerated {

  HtmlElementNameGenerated() {}

  /**
   * The {@code a} element.
   */
  public static final HtmlElementName A = HtmlElementName.createNormal("a");

  /**
   * The {@code meta} element.
   */
  public static final HtmlElementName META = HtmlElementName.createVoid("meta");

  /**
   * The {@code option} element.
   */
  public static final HtmlElementName OPTION = HtmlElementName.createNormal("option");

  /**
   * The {@code select} element.
   */
  public static final HtmlElementName SELECT = HtmlElementName.createNormal("select");

  /**
   * The {@code title} element.
   */
  public static final HtmlElementName TITLE = HtmlElementName.createNormal("title");

}
"""
    );
  }

}
