/*
 * Copyright (C) 2015-2023 Objectos Software LTDA.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package objectos.selfgen.html;

import static org.testng.Assert.assertEquals;

import org.testng.annotations.Test;

public class HtmlAttributeNameGeneratedTest {

  @Test(description = "it should generate an class for each distinct attribute defined")
  public void execute() {
    HtmlSelfGen spec;
    spec = TestingHtmlSelfGen.SPEC;

    HtmlAttributeNameGenerated template;
    template = new HtmlAttributeNameGenerated(spec);

    assertEquals(
        template.toString(),

"""
/*
 * Copyright (C) 2015-2024 Objectos Software LTDA.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package objectos.way;

// Generated by objectos.selfgen.HtmlSpec. Do not edit!
abstract class HtmlAttributeNameGenerated {

  HtmlAttributeNameGenerated() {}

  /**
   * The {@code disabled} attribute.
   */
  public static final Html.AttributeName DISABLED = HtmlAttributeName.create("disabled", true);

  /**
   * The {@code label} attribute.
   */
  public static final Html.AttributeName LABEL = HtmlAttributeName.create("label", false);

  /**
   * The {@code lang} attribute.
   */
  public static final Html.AttributeName LANG = HtmlAttributeName.create("lang", false);

  /**
   * The {@code title} attribute.
   */
  public static final Html.AttributeName TITLE = HtmlAttributeName.create("title", false);

}
"""
    );
  }

}
