/*
 * Copyright (C) 2015-2023 Objectos Software LTDA.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package objectos.selfgen.html;

import static org.testng.Assert.assertEquals;

import org.testng.annotations.Test;

public class HtmlGeneratedTest {

  @Test
  public void execute() {
    HtmlSelfGen spec;
    spec = new HtmlSelfGen() {
      @Override
      protected final void definition() {
        template()
            .skipAttribute("title");

        rootElement()
            .attribute("lang")
            .attribute("title");

        element("a").simpleName("Anchor");

        element("title");

        element("meta").noEndTag();

        element("option")
            .attribute("disabled").booleanType()
            .attribute("label");

        element("select")
            .attribute("disabled").booleanType();
      }
    }.prepare();

    HtmlGenerated template;
    template = new HtmlGenerated(spec);

    assertEquals(
        template.toString(),

        """
/*
 * Copyright (C) 2015-2024 Objectos Software LTDA.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package objectos.way;

/**
 * The Objectos HTML main class.
 */
public final class Html {

  private Html() {}

  // The code below was generated by objectos.selfgen.HtmlSpec. Do not edit!

  /**
   * Represents an instruction that generates part of the output of an HTML
   * template.
   *
   * <p>
   * Unless noted references to a particular instruction MUST NOT be reused.
   */
  public sealed interface Instruction {}

  /**
   * An attribute instruction in an HTML template.
   */
  public sealed interface AttributeInstruction extends Instruction {}

  private static final class HtmlAttributeInstruction implements AttributeInstruction {}

  static final AttributeInstruction ATTRIBUTE = new HtmlAttributeInstruction();

  /**
   * Provides methods the HTML attributes template methods.
   */
  public static abstract class TemplateAttributes {

    TemplateAttributes() {}

    /**
     * Generates the {@code disabled} boolean attribute.
     *
     * @return an instruction representing this attribute.
     */
    protected final AttributeInstruction disabled() {
      return $compiler().disabled();
    }

    /**
     * Generates the {@code label} attribute with the specified value.
     *
     * @param value
     *        the value of the attribute
     *
     * @return an instruction representing this attribute.
     */
    protected final AttributeInstruction label(String value) {
      return $compiler().label(value);
    }

    /**
     * Generates the {@code lang} attribute with the specified value.
     *
     * @param value
     *        the value of the attribute
     *
     * @return an instruction representing this attribute.
     */
    protected final AttributeInstruction lang(String value) {
      return $compiler().lang(value);
    }

    abstract CompilerAttributes $compiler();

  }

  /**
   * Provides the HTML attributes compiler methods.
   */
  public sealed interface CompilerAttributes permits Compiler {

    /**
     * Compiles the {@code disabled} boolean attribute.
     *
     * @return an instruction representing this attribute.
     */
    AttributeInstruction disabled();

    /**
     * Compiles the {@code label} attribute with the specified value.
     *
     * @param value
     *        the value of the attribute
     *
     * @return an instruction representing this attribute.
     */
    AttributeInstruction label(String value);

    /**
     * Compiles the {@code lang} attribute with the specified value.
     *
     * @param value
     *        the value of the attribute
     *
     * @return an instruction representing this attribute.
     */
    AttributeInstruction lang(String value);

  }

}
"""
    );
  }

}